server:
  port: ${SERVER_PORT:8081}

# db없이 test #################
#spring:
#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/delivery}
##    username: ${SPRING_DATASOURCE_USERNAME:postgres}
##    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
#    username: leeeunbin
#    password: 4622
#    driver-class-name: org.postgresql.Driver

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#################
management:
  endpoints:
    web:
      exposure:
        include: health,info